sonar.projectKey=dev-ana-lopes_service-order-os-service
sonar.organization=dev-ana-lopes
sonar.projectName=service-order-os-service
sonar.sources=src
sonar.tests=tests
sonar.python.coverage.reportPaths=coverage.xml
sonar.sourceEncoding=UTF-8
