apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: service-order-os-service
  namespace: service-order
  annotations:
    kubernetes.io/ingress.class: traefik
spec:
  rules:
    - http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: service-order-os-service
                port:
                  number: 80

