apiVersion: batch/v1
kind: Job
metadata:
  name: service-order-os-service-migrate
  namespace: service-order
spec:
  backoffLimit: 3
  template:
    spec:
      restartPolicy: OnFailure
      containers:
        - name: migrate
          image: __API_IMAGE__
          imagePullPolicy: IfNotPresent
          envFrom:
            - configMapRef:
                name: service-order-os-service-config
            - secretRef:
                name: service-order-os-service-secret
          command:
            - alembic
            - -c
            - alembic/alembic.ini
            - upgrade
            - head

