apiVersion: v1
kind: Secret
metadata:
  name: service-order-os-service-secret
  namespace: service-order
type: Opaque
stringData:
  DATABASE_URL: "${DATABASE_URL}"
  RABBITMQ_URL: "${RABBITMQ_URL}"
  JWT_SECRET: "${JWT_SECRET}"
  CUSTOMER_JWT_SECRET: "${CUSTOMER_JWT_SECRET}"
  APPROVAL_TOKEN_SECRET: "${APPROVAL_TOKEN_SECRET}"
  SMTP_USERNAME: "${SMTP_USERNAME}"
  SMTP_PASSWORD: "${SMTP_PASSWORD}"
  DD_API_KEY: "${DD_API_KEY}"

