apiVersion: v1
kind: Service
metadata:
  name: service-order-os-service
  namespace: service-order
  labels:
    app: service-order-os-service
spec:
  type: ClusterIP
  selector:
    app: service-order-os-service
  ports:
    - name: http
      port: 80
      targetPort: 8000

