apiVersion: v1
kind: Secret
metadata:
  name: rabbitmq-secret
  namespace: service-order
type: Opaque
stringData:
  RABBITMQ_DEFAULT_USER: service-order
  RABBITMQ_DEFAULT_PASS: change-me
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq
  namespace: service-order
  labels:
    app: rabbitmq
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rabbitmq
  template:
    metadata:
      labels:
        app: rabbitmq
    spec:
      containers:
        - name: rabbitmq
          image: rabbitmq:3.13-management-alpine
          ports:
            - containerPort: 5672
            - containerPort: 15672
          envFrom:
            - secretRef:
                name: rabbitmq-secret
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 512Mi
---
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
  namespace: service-order
spec:
  selector:
    app: rabbitmq
  ports:
    - name: amqp
      port: 5672
      targetPort: 5672
    - name: management
      port: 15672
      targetPort: 15672
